<script>
document.addEventListener('alpine:init',()=>Alpine.data('preparationsDetailOnboarding',()=>({
open:@js($preparationsDetailOnboarding->status==='started'),step:@js((int)$preparationsDetailOnboarding->current_step),rect:null,panelStyle:'position:fixed;z-index:10001;left:16px;top:16px;width:min(440px,calc(100% - 32px))',steps:[
{target:'intro',title:'Detail Evidence Standar',text:'Ini adalah ruang kerja evidence untuk {{ addslashes($standard->code) }}.',func:'Semua auditee yang ditugaskan pada standar ini dapat melihat evidence bersama.'},
{target:'prodi-filter',title:'Pilih Program Studi',text:'Pilih prodi sebelum mengunggah dokumen atau memperbarui progres.',func:'Dokumen dan status penyelesaian disimpan terpisah untuk setiap prodi.'},
{target:'stages',title:'Tahap Evidence',text:'Bagian kiri berisi tahap yang dibuat admin maupun auditee.',func:'Anda dapat membuat tahap sendiri serta mengedit atau menghapus tahap milik sendiri.'},
{target:'tasks',title:'Task dan Dokumen',text:'Bagian kanan menampilkan task pada tahap yang aktif.',func:'Task milik auditee lain dapat dilihat, tetapi hanya pemilik yang dapat mengubah atau menghapusnya.'},
{target:'intro',title:'Panduan Selesai',text:'Anda siap mengelola evidence standar ini.',func:'Klik Lihat Panduan untuk mengulang tur kapan saja.'}],
init(){if(this.step>=this.steps.length)this.step=0;this.$watch('step',()=>this.position());addEventListener('resize',()=>this.position());addEventListener('scroll',()=>this.position(),true);addEventListener('restart-preparations-detail-onboarding',()=>this.restart());if(this.open)this.$nextTick(()=>this.position())},
position(){if(!this.open)return;const e=document.querySelector(`[data-onboarding-preparations-detail="${this.steps[this.step].target}"]`);if(!e){this.rect=null;return}e.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{const r=e.getBoundingClientRect();this.rect={top:r.top-6,left:r.left-6,width:r.width+12,height:r.height+12};this.place(r)},180)},
place(t){const g=18,m=16,w=Math.min(440,innerWidth-m*2),h=Math.min(390,innerHeight-m*2);let l,p;if(innerWidth<640){l=m;p=Math.max(m,innerHeight-h-m)}else if(t.right+g+w<=innerWidth-m){l=t.right+g;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else if(t.left-g-w>=m){l=t.left-g-w;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else{l=Math.min(Math.max(m,t.left),innerWidth-w-m);p=Math.max(m,t.top-g-h)}this.panelStyle=`position:fixed;z-index:10001;left:${l}px;top:${p}px;width:${w}px;max-height:${h}px;overflow-y:auto`},
async save(status){await fetch(@js(route('onboarding.internal-preparations-detail.progress')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())},body:JSON.stringify({current_step:this.step,status})})},
next(){if(this.step===this.steps.length-1){this.save('completed');this.open=false}else{this.step++;this.save('started')}},back(){if(this.step>0){this.step--;this.save('started')}},skip(){if(confirm('Lewati panduan detail Evidence Standar?')){this.save('skipped');this.open=false}},async restart(){await fetch(@js(route('onboarding.internal-preparations-detail.restart')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())}});this.step=0;this.open=true;this.$nextTick(()=>this.position())}})))
</script>
<div x-data="preparationsDetailOnboarding" x-show="open" x-cloak style="position:fixed;inset:0;z-index:9999" role="dialog" aria-modal="true">
<div x-show="!rect" style="position:absolute;inset:0;background:rgba(2,6,23,.72)"></div><template x-if="rect"><div class="pointer-events-none"><div :style="`position:fixed;left:0;right:0;top:0;height:${Math.max(0,rect.top)}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;top:${rect.top}px;width:${Math.max(0,rect.left)}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:${rect.left+rect.width}px;right:0;top:${rect.top}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;right:0;top:${rect.top+rect.height}px;bottom:0;background:rgba(2,6,23,.72)`"></div></div></template>
<div x-show="rect" class="pointer-events-none rounded-xl border-4 border-indigo-400" :style="`position:fixed;z-index:10000;top:${rect?.top}px;left:${rect?.left}px;width:${rect?.width}px;height:${rect?.height}px`"></div>
<div class="rounded-2xl bg-white p-5 text-slate-900 shadow-2xl dark:bg-slate-800 dark:text-white" :style="panelStyle"><div class="mb-3 flex justify-between"><span class="text-xs font-bold uppercase text-indigo-500" x-text="`Langkah ${step+1} dari ${steps.length}`"></span><span class="text-xs text-slate-400">Detail Evidence</span></div><h3 class="text-lg font-bold" x-text="steps[step].title"></h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300" x-text="steps[step].text"></p><div class="mt-3 rounded-xl border p-3 text-sm" style="border-color:rgba(99,102,241,.38);background:rgba(79,70,229,.14);color:inherit"><b style="color:#818cf8">Fungsi:</b> <span x-text="steps[step].func"></span></div><div class="mt-5 h-1.5 rounded-full bg-slate-200 dark:bg-slate-700"><div class="h-full rounded-full bg-indigo-600" :style="`width:${((step+1)/steps.length)*100}%`"></div></div><div class="mt-5 gap-2" style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr))"><button @click="skip" class="h-10 rounded-xl border text-xs font-bold" style="border-color:rgba(251,113,133,.55);color:#fb7185">Lewati</button><button @click="back" :disabled="step===0" class="h-10 rounded-xl text-sm font-bold disabled:opacity-40" style="background:rgba(100,116,139,.35);color:inherit">Kembali</button><button @click="next" class="h-10 rounded-xl bg-indigo-600 text-sm font-bold text-white" x-text="step===steps.length-1?'Selesai':'Lanjut'"></button></div></div></div>
