<script>
document.addEventListener('alpine:init',()=>Alpine.data('cycleOnboarding',()=>({
open:@js($amiCycleOnboarding->status==='started'),step:@js((int)$amiCycleOnboarding->current_step),rect:null,panelStyle:'position:fixed;z-index:10001;left:16px;top:16px;width:min(440px,calc(100% - 32px))',
steps:[
{target:'intro',title:'Siklus Audit Mutu Internal',text:'Halaman ini mengatur periode dan pelaksanaan AMI.',func:'Menjadi pusat pengelolaan siklus, submission program studi, auditee, dan auditor.'},
{target:'new-button',title:'Siklus Baru',text:'Gunakan tombol ini untuk membuka formulir siklus baru.',func:'Memulai periode audit baru dengan nama dan rentang tanggal tertentu.'},
{target:'form',title:'Formulir Siklus',text:'Isi judul, tanggal mulai, dan tanggal selesai pelaksanaan audit.',func:'Menetapkan identitas dan batas waktu resmi pelaksanaan satu siklus AMI.'},
{target:'stats',title:'Ringkasan Siklus',text:'Kartu menampilkan jumlah siklus aktif, selesai, dan submission.',func:'Memberikan gambaran cepat beban dan progres pelaksanaan AMI.'},
{target:'history',title:'Riwayat Siklus',text:'Setiap kartu siklus menampilkan status, periode, dan jumlah submission.',func:'Membuka pengelolaan siklus untuk menambah auditee, standar, dan menugaskan auditor.'},
{target:'intro',title:'Panduan Siklus AMI Selesai',text:'Klik Lihat Panduan untuk mengulang tur ini.',func:'Progres panduan disimpan khusus untuk akun admin Anda.'}],
init(){this.$watch('step',()=>this.position());addEventListener('resize',()=>this.position());addEventListener('scroll',()=>this.position(),true);addEventListener('restart-cycle-onboarding',()=>this.restart());if(this.open)this.$nextTick(()=>this.position())},
position(){if(!this.open)return;const s=this.steps[this.step];window.dispatchEvent(new CustomEvent('onboarding-cycle-form',{detail:s.target==='form'}));setTimeout(()=>{const e=document.querySelector(`[data-onboarding-cycle="${s.target}"]`);if(!e){this.rect=null;return}e.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{const r=e.getBoundingClientRect();this.rect={top:r.top-6,left:r.left-6,width:r.width+12,height:r.height+12};this.place(r)},160)},80)},
place(t){const g=18,m=16,w=Math.min(440,innerWidth-m*2),h=Math.min(390,innerHeight-m*2);let l,p;if(innerWidth<640){l=m;p=Math.max(m,innerHeight-h-m)}else if(t.right+g+w<=innerWidth-m){l=t.right+g;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else if(t.left-g-w>=m){l=t.left-g-w;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else if(t.bottom+g+h<=innerHeight-m){l=Math.min(Math.max(m,t.left),innerWidth-w-m);p=t.bottom+g}else{l=Math.min(Math.max(m,t.left),innerWidth-w-m);p=Math.max(m,t.top-g-h)}this.panelStyle=`position:fixed;z-index:10001;left:${l}px;top:${p}px;width:${w}px;max-height:${h}px;overflow-y:auto`},
async save(status){await fetch(@js(route('onboarding.admin-ami-cycles.progress')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())},body:JSON.stringify({current_step:this.step,status})})},
next(){if(this.step===this.steps.length-1){this.save('completed');this.open=false}else{this.step++;this.save('started')}},back(){if(this.step>0){this.step--;this.save('started')}},skip(){if(confirm('Lewati panduan Siklus AMI? Panduan dapat dibuka kembali.')){this.save('skipped');this.open=false;window.dispatchEvent(new CustomEvent('onboarding-cycle-form',{detail:false}))}},async restart(){await fetch(@js(route('onboarding.admin-ami-cycles.restart')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())}});this.step=0;this.open=true;this.$nextTick(()=>this.position())}
})))
</script>
<div x-data="cycleOnboarding" x-show="open" x-cloak style="position:fixed;inset:0;z-index:9999" role="dialog" aria-modal="true" aria-label="Panduan Siklus AMI"><div x-show="!rect" style="position:absolute;inset:0;background:rgba(2,6,23,.72)"></div><template x-if="rect"><div class="pointer-events-none"><div :style="`position:fixed;left:0;right:0;top:0;height:${Math.max(0,rect.top)}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;top:${rect.top}px;width:${Math.max(0,rect.left)}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:${rect.left+rect.width}px;right:0;top:${rect.top}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;right:0;top:${rect.top+rect.height}px;bottom:0;background:rgba(2,6,23,.72)`"></div></div></template><div x-show="rect" class="pointer-events-none rounded-xl border-4 border-blue-400" :style="`position:fixed;z-index:10000;top:${rect?.top}px;left:${rect?.left}px;width:${rect?.width}px;height:${rect?.height}px`"></div><div class="rounded-2xl bg-white p-5 text-slate-900 shadow-2xl dark:bg-slate-800 dark:text-white" :style="panelStyle"><div class="mb-3 flex justify-between"><span class="text-xs font-bold uppercase text-blue-500" x-text="`Langkah ${step+1} dari ${steps.length}`"></span><span class="text-xs text-slate-400">Siklus AMI</span></div><h3 class="text-lg font-bold" x-text="steps[step].title"></h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300" x-text="steps[step].text"></p><div class="mt-3 rounded-xl border p-3 text-sm" style="border-color:rgba(59,130,246,.38);background:rgba(37,99,235,.14);color:inherit"><b style="color:#60a5fa">Fungsi:</b> <span x-text="steps[step].func"></span></div><div class="mt-5 h-1.5 rounded-full bg-slate-200 dark:bg-slate-700"><div class="h-full rounded-full bg-blue-600" :style="`width:${((step+1)/steps.length)*100}%`"></div></div><div class="mt-5 grid grid-cols-3 gap-2"><button @click="skip" class="h-10 rounded-xl border border-rose-200 text-xs font-bold text-rose-600">Lewati</button><button @click="back" :disabled="step===0" class="h-10 rounded-xl bg-slate-100 text-sm font-bold disabled:opacity-40 dark:bg-slate-700">Kembali</button><button @click="next" class="h-10 rounded-xl bg-blue-600 text-sm font-bold text-white" x-text="step===steps.length-1?'Selesai':'Lanjut'"></button></div></div></div>
