<script>
document.addEventListener('alpine:init',()=>Alpine.data('auditeeOnboarding',()=>({open:@js($auditeeOnboarding?->status==='started'),step:@js((int)($auditeeOnboarding?->current_step??0)),rect:null,panelStyle:'position:fixed;z-index:10001;left:16px;top:16px;width:min(440px,calc(100% - 32px))',steps:[
{target:'welcome',title:'Selamat Datang, Auditee',text:'Dashboard membantu Anda memantau tugas dan progres pengisian AMI.',func:'Memberikan ringkasan pekerjaan audit yang perlu disiapkan.'},
{target:'ami-menu',title:'Audit & AMI',text:'Menu utama untuk membuka tugas Audit Mutu Internal.',func:'Mengakses halaman pengisian referensi, status, dan bukti AMI.'},
{target:'auditee-ami-submenu',title:'Pengisian AMI',text:'Buka daftar submission yang ditugaskan kepada Anda.',func:'Memilih standar, mengisi status pertanyaan, menambahkan referensi dan evidence, lalu submit.'},
{target:'dashboard-filters',title:'Filter Dashboard',text:'Saring informasi berdasarkan periode dan unit.',func:'Membantu menampilkan data yang paling relevan dengan penugasan Anda.'},
{target:'summary-cards',title:'Ringkasan Utama',text:'Lihat jumlah assessment, temuan, dan tindak lanjut.',func:'Mengetahui kondisi pekerjaan audit secara cepat.'},
{target:'recent-activity',title:'Aktivitas Terbaru',text:'Bagian ini menampilkan pekerjaan terbaru.',func:'Memudahkan Anda melanjutkan aktivitas tanpa mencari ulang.'},
{target:'user-menu',title:'Menu Pengguna',text:'Gunakan menu ini untuk pengajuan akses standar.',func:'Meminta akses ketika standar yang menjadi tanggung jawab Anda belum tersedia.'},
{target:'auditee-request-submenu',title:'Ajukan Standar',text:'Pilih standar yang perlu ditambahkan ke akun Anda.',func:'Mengirim permintaan kepada admin untuk ditinjau dan disetujui.'},
{target:'welcome',title:'Panduan Auditee Selesai',text:'Klik Lihat Panduan jika ingin mengulang tur.',func:'Progres panduan tersimpan pada akun auditee Anda.'}],
init(){this.$watch('step',()=>this.position());addEventListener('resize',()=>this.position());addEventListener('scroll',()=>this.position(),true);addEventListener('restart-auditee-onboarding',()=>this.restart());if(this.open)this.$nextTick(()=>this.position())},position(){if(!this.open)return;document.querySelectorAll('[data-onboarding-active]').forEach(n=>n.removeAttribute('data-onboarding-active'));const e=document.querySelector(`[data-onboarding="${this.steps[this.step].target}"]`);if(!e){this.rect=null;return}const menu=e.closest('[data-onboarding$="-menu"]');e.setAttribute('data-onboarding-active','true');dispatchEvent(new CustomEvent('onboarding-open-menu',{detail:menu?.dataset.onboarding||null}));setTimeout(()=>{e.scrollIntoView({behavior:'smooth',block:'center'});const r=e.getBoundingClientRect();this.rect={top:r.top-6,left:r.left-6,width:r.width+12,height:r.height+12};this.place(r)},180)},place(t){const g=18,m=16,w=Math.min(440,innerWidth-m*2),h=Math.min(390,innerHeight-m*2);let l,p;if(innerWidth<640){l=m;p=Math.max(m,innerHeight-h-m)}else if(t.right+g+w<=innerWidth-m){l=t.right+g;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else if(t.left-g-w>=m){l=t.left-g-w;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else if(t.bottom+g+h<=innerHeight-m){l=Math.min(Math.max(m,t.left),innerWidth-w-m);p=t.bottom+g}else{l=Math.min(Math.max(m,t.left),innerWidth-w-m);p=Math.max(m,t.top-g-h)}this.panelStyle=`position:fixed;z-index:10001;left:${l}px;top:${p}px;width:${w}px;max-height:${h}px;overflow-y:auto`},closeMenus(){document.querySelectorAll('[data-onboarding-active]').forEach(n=>n.removeAttribute('data-onboarding-active'));dispatchEvent(new CustomEvent('onboarding-open-menu',{detail:null}))},async save(status){await fetch(@js(route('onboarding.dashboard-auditee.progress')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())},body:JSON.stringify({current_step:this.step,status})})},next(){if(this.step===this.steps.length-1){this.save('completed');this.closeMenus();this.open=false}else{this.step++;this.save('started')}},back(){if(this.step>0){this.step--;this.save('started')}},skip(){if(confirm('Lewati panduan auditee? Panduan dapat dibuka kembali.')){this.save('skipped');this.closeMenus();this.open=false}},async restart(){await fetch(@js(route('onboarding.dashboard-auditee.restart')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())}});this.step=0;this.open=true;this.$nextTick(()=>this.position())}})))
</script>
<div x-data="auditeeOnboarding" x-show="open" x-cloak style="position:fixed;inset:0;z-index:9999" role="dialog" aria-modal="true"><div x-show="!rect" style="position:absolute;inset:0;background:rgba(2,6,23,.72)"></div><template x-if="rect"><div class="pointer-events-none"><div :style="`position:fixed;left:0;right:0;top:0;height:${Math.max(0,rect.top)}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;top:${rect.top}px;width:${Math.max(0,rect.left)}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:${rect.left+rect.width}px;right:0;top:${rect.top}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;right:0;top:${rect.top+rect.height}px;bottom:0;background:rgba(2,6,23,.72)`"></div></div></template><div x-show="rect" class="pointer-events-none rounded-xl border-4 border-emerald-400" :style="`position:fixed;z-index:10000;top:${rect?.top}px;left:${rect?.left}px;width:${rect?.width}px;height:${rect?.height}px`"></div><div class="rounded-2xl bg-white p-5 text-slate-900 shadow-2xl dark:bg-slate-800 dark:text-white" :style="panelStyle"><div class="mb-3 flex justify-between"><span class="text-xs font-bold uppercase text-emerald-500" x-text="`Langkah ${step+1} dari ${steps.length}`"></span><span class="text-xs text-slate-400">Panduan Auditee</span></div><h3 class="text-lg font-bold" x-text="steps[step].title"></h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300" x-text="steps[step].text"></p><div class="mt-3 rounded-xl border p-3 text-sm" style="border-color:rgba(16,185,129,.38);background:rgba(5,150,105,.14);color:inherit"><b style="color:#34d399">Fungsi:</b> <span x-text="steps[step].func"></span></div><div class="mt-5 h-1.5 rounded-full bg-slate-200 dark:bg-slate-700"><div class="h-full rounded-full bg-emerald-600" :style="`width:${((step+1)/steps.length)*100}%`"></div></div><div class="mt-5 grid grid-cols-3 gap-2"><button @click="skip" class="h-10 rounded-xl border border-rose-200 text-xs font-bold text-rose-600">Lewati</button><button @click="back" :disabled="step===0" class="h-10 rounded-xl bg-slate-100 text-sm font-bold disabled:opacity-40 dark:bg-slate-700">Kembali</button><button @click="next" class="h-10 rounded-xl bg-emerald-600 text-sm font-bold text-white" x-text="step===steps.length-1?'Selesai':'Lanjut'"></button></div></div></div>
