<x-app-layout>
    <div class="mx-auto w-full max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <nav class="mb-5 flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400"><a href="{{ route('dashboard') }}" class="hover:text-blue-600">Dashboard</a><span>/</span><span class="font-medium text-slate-800 dark:text-slate-200">Pengajuan Standar</span></nav>

        <div class="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <div><p class="text-sm font-semibold text-blue-600 dark:text-blue-400">Manajemen Akses</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-3xl">Pengajuan Standar</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Tinjau permintaan akses standar dan aktivasi akun pengguna.</p></div>
            @if($counts['pending'])<span class="inline-flex w-fit items-center gap-2 rounded-full bg-amber-50 px-3 py-2 text-sm font-bold text-amber-700 ring-1 ring-amber-600/20 dark:bg-amber-500/10 dark:text-amber-400"><span class="h-2 w-2 animate-pulse rounded-full bg-amber-500"></span>{{ $counts['pending'] }} perlu ditinjau</span>@endif
        </div>

        @if(session('success'))<div x-data="{show:true}" x-show="show" x-init="setTimeout(() => show=false, 4000)" class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-700 dark:border-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-400">{{ session('success') }}</div>@endif
        @if(session('error'))<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-medium text-rose-700 dark:border-rose-800 dark:bg-rose-500/10 dark:text-rose-400">{{ session('error') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 dark:border-rose-800 dark:bg-rose-500/10 dark:text-rose-400">{{ $errors->first() }}</div>@endif

        <div class="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-3 lg:gap-5">
            @foreach([
                'pending' => ['label' => 'Menunggu', 'class' => 'bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-400'],
                'approved' => ['label' => 'Disetujui', 'class' => 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400'],
                'rejected' => ['label' => 'Ditolak', 'class' => 'bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-400'],
            ] as $key => $meta)
                <a href="{{ route('admin.role-requests.index', ['status' => $key]) }}" class="flex items-center justify-between rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:bg-slate-800 {{ $status === $key ? 'border-blue-500 ring-2 ring-blue-500/10 dark:border-blue-500' : 'border-slate-200 dark:border-slate-700' }}"><div><p class="text-sm font-semibold text-slate-500 dark:text-slate-400">{{ $meta['label'] }}</p><p class="mt-1 text-3xl font-bold text-slate-950 dark:text-white">{{ number_format($counts[$key]) }}</p></div><span class="flex h-11 w-11 items-center justify-center rounded-xl {{ $meta['class'] }}"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6-2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></span></a>
            @endforeach
        </div>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800">
            <div class="flex flex-col gap-3 border-b border-slate-200 p-4 dark:border-slate-700 sm:flex-row sm:items-center sm:justify-between lg:p-5">
                <div class="flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1 dark:bg-slate-900">
                    @foreach(['pending'=>'Menunggu','approved'=>'Disetujui','rejected'=>'Ditolak','all'=>'Semua'] as $key=>$label)<a href="{{ route('admin.role-requests.index', ['status'=>$key, 'search'=>$search ?: null]) }}" class="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold transition {{ $status === $key ? 'bg-white text-blue-700 shadow-sm dark:bg-slate-700 dark:text-blue-300' : 'text-slate-500 hover:text-slate-800 dark:text-slate-400' }}">{{ $label }}</a>@endforeach
                </div>
                <form method="GET" class="flex gap-2"><input type="hidden" name="status" value="{{ $status }}"><label class="relative"><svg class="absolute left-3 top-2.5 h-5 w-5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg><input name="search" value="{{ $search }}" maxlength="100" placeholder="Cari nama atau email..." class="h-10 w-full rounded-xl border-slate-300 pl-10 text-sm dark:border-slate-600 dark:bg-slate-900 sm:w-64"></label>@if($search)<a href="{{ route('admin.role-requests.index', ['status'=>$status]) }}" class="inline-flex h-10 items-center rounded-xl border border-slate-300 px-3 text-xs font-bold dark:border-slate-600">Reset</a>@endif</form>
            </div>

            <div class="divide-y divide-slate-100 dark:divide-slate-700">
                @forelse($requests as $roleRequest)
                    @php
                        $initials = collect(explode(' ', $roleRequest->user->name))->take(2)->map(fn($part) => strtoupper(substr($part, 0, 1)))->implode('');
                        [$statusLabel, $statusClass] = match($roleRequest->status) {
                            'approved' => ['Disetujui', 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400'],
                            'rejected' => ['Ditolak', 'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-400'],
                            default => ['Menunggu', 'bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-400'],
                        };
                    @endphp
                    <article x-data="{ approveOpen:false, rejectOpen:false }" class="p-4 transition hover:bg-slate-50/70 dark:hover:bg-slate-700/20 sm:p-5">
                        <div class="flex flex-col gap-5 lg:flex-row lg:items-start">
                            <div class="flex min-w-0 flex-1 gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700 dark:bg-blue-500/15 dark:text-blue-300">{{ $initials }}</span><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold text-slate-900 dark:text-white">{{ $roleRequest->user->name }}</h2><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $statusClass }}">{{ $statusLabel }}</span>@if(!$roleRequest->user->is_active)<span class="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-500 dark:bg-slate-700 dark:text-slate-300">Akun belum aktif</span>@endif</div><p class="mt-0.5 text-xs text-slate-400">{{ $roleRequest->user->email }} · diajukan {{ $roleRequest->created_at->diffForHumans() }}</p><div class="mt-3 flex flex-wrap gap-1.5">@foreach($roleRequest->requested_role as $code)<span class="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700 dark:bg-blue-500/10 dark:text-blue-400">{{ $code }}</span>@endforeach</div>@if($roleRequest->reason)<p class="mt-3 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300"><span class="font-semibold">Alasan:</span> {{ $roleRequest->reason }}</p>@endif @if($roleRequest->review_note)<p class="mt-2 text-xs text-slate-500 dark:text-slate-400"><span class="font-semibold">Catatan reviewer:</span> {{ $roleRequest->review_note }}</p>@endif</div></div>
                            @if($roleRequest->isPending())<div class="flex shrink-0 gap-2"><button @click="rejectOpen=true" class="h-10 rounded-xl border border-rose-200 px-4 text-sm font-bold text-rose-600 hover:bg-rose-50 dark:border-rose-900 dark:text-rose-400 dark:hover:bg-rose-500/10">Tolak</button><button @click="approveOpen=true" class="h-10 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white shadow-sm hover:bg-emerald-700">Setujui</button></div>@else<div class="shrink-0 text-right text-xs text-slate-400">@if($roleRequest->reviewer)<p>Diproses oleh {{ $roleRequest->reviewer->name }}</p>@endif<p class="mt-1">{{ $roleRequest->reviewed_at?->translatedFormat('d M Y, H:i') }}</p></div>@endif
                        </div>

                        @if($roleRequest->isPending())
                            <div x-show="approveOpen" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm"><div @click.outside="approveOpen=false" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-800"><span class="flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400"><svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg></span><h3 class="mt-4 text-xl font-bold">Setujui Pengajuan?</h3><p class="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Berikan akses <strong>{{ implode(', ', $roleRequest->requested_role) }}</strong> kepada {{ $roleRequest->user->name }}{{ !$roleRequest->user->is_active ? ' sekaligus mengaktifkan akunnya' : '' }}.</p><form method="POST" action="{{ route('admin.role-requests.approve', $roleRequest) }}" class="mt-5">@csrf @method('PATCH')<label class="text-sm font-semibold">Catatan <span class="font-normal text-slate-400">(opsional)</span><textarea name="review_note" maxlength="500" rows="3" class="mt-1.5 w-full rounded-xl border-slate-300 dark:border-slate-600 dark:bg-slate-900"></textarea></label><div class="mt-5 flex gap-3"><button type="button" @click="approveOpen=false" class="h-11 flex-1 rounded-xl bg-slate-100 text-sm font-bold dark:bg-slate-700">Batal</button><button class="h-11 flex-1 rounded-xl bg-emerald-600 text-sm font-bold text-white">Ya, Setujui</button></div></form></div></div>
                            <div x-show="rejectOpen" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm"><div @click.outside="rejectOpen=false" class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-800"><span class="flex h-12 w-12 items-center justify-center rounded-full bg-rose-100 text-rose-600 dark:bg-rose-500/10 dark:text-rose-400"><svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></span><h3 class="mt-4 text-xl font-bold">Tolak Pengajuan?</h3><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Berikan alasan yang jelas agar pengguna dapat memperbaiki pengajuannya.</p><form method="POST" action="{{ route('admin.role-requests.reject', $roleRequest) }}" class="mt-5">@csrf @method('PATCH')<label class="text-sm font-semibold">Alasan penolakan <span class="text-rose-500">*</span><textarea name="review_note" required maxlength="500" rows="3" class="mt-1.5 w-full rounded-xl border-slate-300 dark:border-slate-600 dark:bg-slate-900"></textarea></label><div class="mt-5 flex gap-3"><button type="button" @click="rejectOpen=false" class="h-11 flex-1 rounded-xl bg-slate-100 text-sm font-bold dark:bg-slate-700">Batal</button><button class="h-11 flex-1 rounded-xl bg-rose-600 text-sm font-bold text-white">Ya, Tolak</button></div></form></div></div>
                        @endif
                    </article>
                @empty
                    <div class="py-16 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-slate-400 dark:bg-slate-700"><svg class="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/></svg></span><p class="mt-4 font-bold">Tidak ada pengajuan</p><p class="mt-1 text-sm text-slate-500">Belum ada data yang sesuai dengan filter.</p></div>
                @endforelse
            </div>
            @if($requests->hasPages())<div class="border-t border-slate-200 px-4 py-4 dark:border-slate-700 sm:px-6">{{ $requests->links() }}</div>@endif
        </section>
    </div>
</x-app-layout>
