<x-app-layout>
    <div class="mx-auto w-full max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8" x-data="amiQuestions()" x-init="init()" @onboarding-ami-select.window="selectStandard($event.detail.id, $event.detail.code, $event.detail.name)">
        <nav class="mb-5 flex gap-2 text-sm text-slate-500"><a href="{{ route('dashboard') }}">Dashboard</a><span>/</span><span>Pertanyaan AMI</span></nav>
        <div data-onboarding-ami-question="intro" class="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-blue-600 dark:text-blue-400">Audit Mutu Internal</p><h1 class="mt-1 text-3xl font-bold text-slate-950 dark:text-white">Bank Pertanyaan AMI</h1><p class="mt-2 text-sm text-slate-500">Pilih satu standar sebelum mengunduh template atau mengimpor pertanyaan.</p></div><div class="flex flex-wrap gap-2"><button type="button" onclick="window.dispatchEvent(new CustomEvent('restart-ami-question-onboarding'))" class="h-11 rounded-xl border border-blue-200 px-4 text-sm font-bold text-blue-600 dark:border-blue-800 dark:text-blue-400">Lihat Panduan</button><a data-onboarding-ami-question="download" :href="standardId ? templateUrl() : '#'" :class="!standardId && 'pointer-events-none opacity-50'" class="inline-flex h-11 items-center rounded-xl border border-slate-300 px-4 text-sm font-bold dark:border-slate-600"><span x-text="standardCode ? 'Unduh Template '+standardCode : 'Pilih Standar'">Pilih Standar</span></a><button data-onboarding-ami-question="import" type="button" @click="if(standardId) importOpen=true" :disabled="!standardId" class="h-11 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">Import Excel</button></div></div>

        @if(session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700 dark:border-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-400">{{ session('success') }}</div>@endif
        @if(session('error'))<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{{ session('error') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif

        <details data-onboarding-ami-question="audit-bank" class="mb-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800">
            <summary class="cursor-pointer px-5 py-4 font-bold">Bank Bidang / Area Audit ({{ $auditAreas->count() }})</summary>
            <p class="border-t border-slate-200 px-5 pt-4 text-xs text-slate-500 dark:border-slate-700">Gunakan kode berikut pada kolom Kode Bidang di template Excel.</p>
            <div class="overflow-x-auto p-5"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-900/50"><tr><th class="px-4 py-3 text-left">Kode</th><th class="px-4 py-3 text-left">Area Audit</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-700">@forelse($auditAreas as $area)<tr><td class="px-4 py-3 font-bold text-blue-600">{{ $area->code }}</td><td class="px-4 py-3">{{ $area->name }}</td></tr>@empty<tr><td colspan="2" class="px-4 py-6 text-center text-slate-500">Bank bidang belum tersedia.</td></tr>@endforelse</tbody></table></div>
        </details>

        @if($previewBatch)
        <section class="mb-6 overflow-hidden rounded-2xl border border-blue-200 bg-white shadow-sm dark:border-blue-900 dark:bg-slate-800">
            <div class="flex flex-col gap-4 border-b border-slate-200 p-5 dark:border-slate-700 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold">Preview Import {{ $previewBatch->standard?->code }}: {{ $previewBatch->original_filename }}</h2><p class="mt-1 text-xs text-slate-500">Periksa hasil validasi sebelum pertanyaan dibuat.</p></div>@if($previewBatch->status === 'ready' && $previewBatch->valid_rows)<form method="POST" action="{{ route('admin.ami.questions.generate', $previewBatch) }}">@csrf<button class="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-bold text-white">Generate {{ $previewBatch->valid_rows }} Pertanyaan</button></form>@endif</div>
            <div class="grid grid-cols-4 gap-3 p-5">@foreach([['Total',$previewBatch->total_rows,'bg-slate-50 dark:bg-slate-700/50'],['Valid',$previewBatch->valid_rows,'bg-emerald-50 dark:bg-emerald-500/10'],['Duplikat',$previewBatch->duplicate_rows,'bg-amber-50 dark:bg-amber-500/10'],['Error',$previewBatch->invalid_rows,'bg-rose-50 dark:bg-rose-500/10']] as [$label,$value,$class])<div class="rounded-xl p-3 text-center {{ $class }}"><p class="text-2xl font-bold">{{ $value }}</p><p class="text-xs text-slate-500">{{ $label }}</p></div>@endforeach</div>
            <div class="max-h-80 overflow-auto border-t border-slate-200 dark:border-slate-700"><table class="w-full text-sm"><thead class="sticky top-0 bg-slate-50 dark:bg-slate-900"><tr><th class="p-3 text-left">Baris</th><th class="p-3 text-left">ST</th><th class="p-3 text-left">No.</th><th class="p-3 text-left">Pertanyaan</th><th class="p-3 text-left">Status</th></tr></thead><tbody class="divide-y dark:divide-slate-700">@foreach($previewBatch->rows as $row)<tr><td class="p-3">{{ $row->row_number }}</td><td class="p-3 font-bold">{{ $row->standard_code }}</td><td class="p-3">{{ $row->question_number }}</td><td class="max-w-xl p-3">{{ $row->question_text }}@if($row->validation_errors)<p class="mt-1 text-xs text-rose-500">{{ implode(', ', $row->validation_errors) }}</p>@endif</td><td class="p-3"><span class="rounded-full px-2 py-1 text-xs font-bold {{ $row->status==='valid'?'bg-emerald-50 text-emerald-700':($row->status==='duplicate'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700') }}">{{ ucfirst($row->status) }}</span></td></tr>@endforeach</tbody></table></div>
        </section>
        @endif

        <section data-onboarding-ami-question="workspace" class="grid gap-6 lg:grid-cols-[300px_1fr]">
            <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 class="mb-3 text-sm font-bold">Daftar Standar</h2><div class="max-h-[620px] space-y-2 overflow-y-auto">@foreach($standards as $standard)@php $code = preg_match('/^ST([1-9])$/i',$standard->code,$m)?'ST0'.$m[1]:$standard->code; @endphp<a href="#" @click.prevent="selectStandard({{ $standard->id }}, @js($standard->code), @js($standard->name))" :class="standardId === {{ $standard->id }} ? 'border-blue-500 bg-blue-50 dark:bg-blue-500/10' : 'border-slate-200 dark:border-slate-700'" class="block rounded-xl border p-3 transition"><div class="flex justify-between gap-2"><span class="font-bold">{{ $standard->code }}</span><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs dark:bg-slate-700">{{ $questionCounts[$code] ?? $questionCounts[$standard->code] ?? 0 }}</span></div><p class="mt-1 truncate text-xs text-slate-500">{{ $standard->name }}</p></a>@endforeach</div></aside>
            <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><div class="border-b border-slate-200 p-5 dark:border-slate-700"><h2 class="font-bold" x-text="standardCode ? standardCode + ' — ' + standardName : 'Pilih Standar'"></h2><div class="mt-4 grid gap-3 sm:grid-cols-2"><input x-model.debounce.350ms="search" @input="load()" placeholder="Cari pertanyaan..." class="h-10 rounded-xl border-slate-300 text-sm dark:border-slate-600 dark:bg-slate-900"><select x-model="prodiId" @change="load()" class="h-10 rounded-xl border-slate-300 text-sm dark:border-slate-600 dark:bg-slate-900"><option value="">Semua Prodi</option>@foreach($prodis as $prodi)<option value="{{ $prodi->id }}">{{ $prodi->name }}</option>@endforeach</select></div></div>
                <div x-show="loading" class="space-y-3 p-5"><template x-for="i in 6"><div class="animate-pulse rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div class="h-4 w-3/4 rounded bg-slate-200 dark:bg-slate-700"></div><div class="mt-3 h-3 w-1/3 rounded bg-slate-100 dark:bg-slate-700"></div></div></template></div>
                <div x-show="!loading && !standardId" class="p-16 text-center text-sm text-slate-500">Pilih ST di sebelah kiri untuk memuat pertanyaan.</div>
                <div x-show="!loading && standardId && questions.length===0" class="p-16 text-center text-sm text-slate-500">Tidak ada pertanyaan sesuai filter.</div>
                <div x-show="!loading" class="divide-y divide-slate-100 dark:divide-slate-700"><template x-for="q in questions" :key="q.id"><article class="flex gap-3 p-5"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-700" x-text="q.question_number"></span><div><p class="font-semibold leading-6" x-text="q.question_text"></p><div class="mt-2 flex flex-wrap gap-2 text-xs text-slate-500"><span class="rounded-full bg-blue-50 px-2 py-0.5 text-blue-700" x-text="q.audit_area ? q.audit_area.code+' — '+q.audit_area.name : q.bidang"></span><span class="rounded-full bg-violet-50 px-2 py-0.5 text-violet-700" x-text="q.prodis.length ? q.prodis.map(p=>p.code).join(', ') : 'Semua Prodi'"></span></div></div></article></template></div>
            </div>
        </section>

        <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-700"><h2 class="font-bold">Riwayat Import</h2><p class="mt-0.5 text-xs text-slate-500">Delapan proses import terakhir.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-900/50"><tr><th class="px-5 py-3 text-left">File</th><th class="px-5 py-3 text-left">Status</th><th class="px-5 py-3 text-left">Hasil</th><th class="px-5 py-3 text-left">Admin</th><th class="px-5 py-3 text-right">Waktu</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-700">@forelse($batches as $batch)<tr><td class="px-5 py-3"><a href="{{ route('admin.ami.questions.index', ['batch'=>$batch->id]) }}" class="font-semibold text-blue-600 hover:underline dark:text-blue-400">{{ $batch->original_filename }}</a></td><td class="px-5 py-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-700">{{ ucfirst($batch->status) }}</span></td><td class="whitespace-nowrap px-5 py-3 text-xs text-slate-500">{{ $batch->imported_rows }} dibuat · {{ $batch->duplicate_rows }} duplikat · {{ $batch->invalid_rows }} error</td><td class="px-5 py-3">{{ $batch->creator?->name ?? '-' }}</td><td class="whitespace-nowrap px-5 py-3 text-right text-xs text-slate-400">{{ $batch->created_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-8 text-center text-slate-500">Belum ada riwayat import.</td></tr>@endforelse</tbody></table></div></section>

        <div x-show="importOpen" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm"><div @click.outside="importOpen=false" class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-800"><h2 class="text-xl font-bold">Import Pertanyaan <span x-text="standardCode"></span></h2><p class="mt-1 text-sm text-slate-500">File hanya dimasukkan ke standar terpilih. Isi Pertanyaan AMI dan Kode Bidang; tulis “Semua” untuk seluruh program studi.</p><p class="mt-2 text-xs text-slate-400">Format: XLSX, XLS, atau CSV. Maksimal 5 MB. Nomor dan urutan dibuat otomatis.</p><form method="POST" action="{{ route('admin.ami.questions.import') }}" enctype="multipart/form-data" class="mt-5" @submit="uploading=true">@csrf<input type="hidden" name="standard_id" :value="standardId"><input type="file" name="file" accept=".xlsx,.xls,.csv" required class="w-full rounded-xl border border-dashed border-slate-300 p-5 text-sm dark:border-slate-600"><div class="mt-5 flex gap-3"><button type="button" @click="importOpen=false" class="h-11 flex-1 rounded-xl bg-slate-100 text-sm font-bold dark:bg-slate-700">Batal</button><button :disabled="uploading" class="h-11 flex-1 rounded-xl bg-blue-600 text-sm font-bold text-white"><span x-show="!uploading">Periksa File</span><span x-show="uploading">Memproses...</span></button></div></form></div></div>
    </div>
    @push('scripts')<script>function amiQuestions(){return{standardId:null,standardCode:'',standardName:'',prodiId:'',search:'',questions:[],loading:false,importOpen:false,uploading:false,controller:null,init(){},templateUrl(){return @js(route('admin.ami.questions.template'))+'?standard_id='+this.standardId},selectStandard(id,code,name){this.standardId=id;this.standardCode=code;this.standardName=name;this.load()},async load(){if(!this.standardId)return;if(this.controller)this.controller.abort();this.controller=new AbortController();this.loading=true;try{const p=new URLSearchParams({standard_id:this.standardId,prodi_id:this.prodiId,search:this.search});const r=await fetch('{{ route('admin.ami.questions.data') }}?'+p,{signal:this.controller.signal,headers:{Accept:'application/json'}});const j=await r.json();this.questions=j.data||[]}catch(e){if(e.name!=='AbortError')this.questions=[]}finally{this.loading=false}}}}</script>@endpush
    @if(auth()->user()->hasRole('admin'))
        @push('scripts')@include('admin.ami.questions.partials.onboarding')@endpush
    @endif
</x-app-layout>
