<script>
document.addEventListener('alpine:init', () => {
    Alpine.data('assessmentOnboarding', () => ({
        open: @js($assessmentOnboarding->status === 'started'), step: @js((int) $assessmentOnboarding->current_step), rect: null,
        panelStyle: 'position:fixed;z-index:10001;left:16px;top:16px;width:min(440px,calc(100% - 32px))',
        steps: [
            {target:'intro',title:'Kelola Assessment',text:'Halaman ini digunakan admin untuk memantau seluruh assessment.',func:'Melihat penugasan, progres, dan hasil assessment setiap program studi.'},
            {target:'create',title:'Buat Assessment',text:'Klik tombol ini untuk membuat penugasan assessment baru.',func:'Menentukan tahun akreditasi, program studi, dan auditor yang bertugas.'},
            {target:'stats',title:'Ringkasan Status',text:'Empat kartu menampilkan kondisi assessment saat ini.',func:'Membandingkan jumlah total, draf, terkirim, dan sudah ditinjau.'},
            {target:'filters',title:'Cari dan Filter',text:'Cari berdasarkan prodi atau assessor, kemudian saring status dan tahun.',func:'Mempercepat pencarian assessment tanpa memeriksa seluruh daftar.'},
            {target:'table',title:'Daftar Assessment',text:'Tabel berisi program studi, tahun, assessor, status, dan waktu dibuat.',func:'Menjadi pusat pemantauan dan akses menuju detail setiap assessment.'},
            {target:'intro',title:'Panduan Assessment Selesai',text:'Gunakan tombol Lihat Panduan untuk mengulang tur.',func:'Progres panduan disimpan khusus untuk akun admin ini.'},
        ],
        init(){this.$watch('step',()=>this.position());window.addEventListener('resize',()=>this.position());window.addEventListener('scroll',()=>this.position(),true);window.addEventListener('restart-assessment-onboarding',()=>this.restart());if(this.open)this.$nextTick(()=>this.position())},
        position(){if(!this.open)return;const el=document.querySelector(`[data-onboarding-assessment="${this.steps[this.step].target}"]`);if(!el){this.rect=null;return}el.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{const r=el.getBoundingClientRect();this.rect={top:r.top-6,left:r.left-6,width:r.width+12,height:r.height+12};this.place(r)},180)},
        place(t){const g=18,m=16,w=Math.min(440,innerWidth-m*2),h=Math.min(390,innerHeight-m*2);let l,p;if(innerWidth<640){l=m;p=Math.max(m,innerHeight-h-m)}else if(t.right+g+w<=innerWidth-m){l=t.right+g;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else if(t.left-g-w>=m){l=t.left-g-w;p=Math.min(Math.max(m,t.top+t.height/2-h/2),innerHeight-h-m)}else if(t.bottom+g+h<=innerHeight-m){l=Math.min(Math.max(m,t.left),innerWidth-w-m);p=t.bottom+g}else{l=Math.min(Math.max(m,t.left),innerWidth-w-m);p=Math.max(m,t.top-g-h)}this.panelStyle=`position:fixed;z-index:10001;left:${l}px;top:${p}px;width:${w}px;max-height:${h}px;overflow-y:auto`},
        async save(status){await fetch(@js(route('onboarding.admin-assessments.progress')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())},body:JSON.stringify({current_step:this.step,status})})},
        next(){if(this.step===this.steps.length-1){this.save('completed');this.open=false}else{this.step++;this.save('started')}},back(){if(this.step>0){this.step--;this.save('started')}},skip(){if(confirm('Lewati panduan Assessment? Anda dapat membukanya kembali melalui tombol Lihat Panduan.')){this.save('skipped');this.open=false}},
        async restart(){await fetch(@js(route('onboarding.admin-assessments.restart')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@js(csrf_token())}});this.step=0;this.open=true;this.$nextTick(()=>this.position())}
    }))
});
</script>
<div x-data="assessmentOnboarding" x-show="open" x-cloak style="position:fixed;inset:0;z-index:9999" role="dialog" aria-modal="true" aria-label="Panduan Kelola Assessment">
    <div x-show="!rect" style="position:absolute;inset:0;background:rgba(2,6,23,.72)"></div>
    <template x-if="rect"><div class="pointer-events-none"><div :style="`position:fixed;left:0;right:0;top:0;height:${Math.max(0,rect.top)}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;top:${rect.top}px;width:${Math.max(0,rect.left)}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:${rect.left+rect.width}px;right:0;top:${rect.top}px;height:${rect.height}px;background:rgba(2,6,23,.72)`"></div><div :style="`position:fixed;left:0;right:0;top:${rect.top+rect.height}px;bottom:0;background:rgba(2,6,23,.72)`"></div></div></template>
    <div x-show="rect" class="pointer-events-none rounded-xl border-4 border-blue-400" :style="`position:fixed;z-index:10000;top:${rect?.top}px;left:${rect?.left}px;width:${rect?.width}px;height:${rect?.height}px`"></div>
    <div class="rounded-2xl bg-white p-5 text-slate-900 shadow-2xl dark:bg-slate-800 dark:text-white" :style="panelStyle"><div class="mb-3 flex justify-between"><span class="text-xs font-bold uppercase text-blue-500" x-text="`Langkah ${step+1} dari ${steps.length}`"></span><span class="text-xs text-slate-400">Assessment Admin</span></div><h3 class="text-lg font-bold" x-text="steps[step].title"></h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300" x-text="steps[step].text"></p><div class="mt-3 rounded-xl border p-3 text-sm" style="border-color:rgba(59,130,246,.38);background:rgba(37,99,235,.14);color:inherit"><b style="color:#60a5fa">Fungsi:</b> <span x-text="steps[step].func"></span></div><div class="mt-5 h-1.5 rounded-full bg-slate-200 dark:bg-slate-700"><div class="h-full rounded-full bg-blue-600" :style="`width:${((step+1)/steps.length)*100}%`"></div></div><div class="mt-5 grid grid-cols-3 gap-2"><button @click="skip" class="h-10 rounded-xl border border-rose-200 text-xs font-bold text-rose-600">Lewati</button><button @click="back" :disabled="step===0" class="h-10 rounded-xl bg-slate-100 text-sm font-bold disabled:opacity-40 dark:bg-slate-700">Kembali</button><button @click="next" class="h-10 rounded-xl bg-blue-600 text-sm font-bold text-white" x-text="step===steps.length-1?'Selesai':'Lanjut'"></button></div></div>
</div>
